version: '3.8'

services:
  server:
    build:
      context: ../  # context is root of your app (Collab/)
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ../:/app
    restart: always
